import React, { Component } from "react";
import "../styles/freemedcure.css";
import CurvedHeader from "../components/curedHeader";
import {
  faLaravel,
  faJsSquare,
  faPhp,
  faBootstrap,
} from "@fortawesome/free-brands-svg-icons";
import { faDatabase } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

class FreeMedCure extends Component {
  video = require("../assets/videos/FreeMedCure_Demo.mp4");
  // backgroundImg = {
  //   bigCircle: require("../assets/img/eclipse_big.svg"),
  //   middleCircle: require("../assets/img/eclipse_middle.svg"),
  //   smallCircle: require("../assets/img/eclipse_small.svg"),
  // };
  data = {
    title: "FreeMedCure",
    subtitle:
      "I have built a web-based data-entry system for my friend who is studying chinese medicine. It helps doctors to keep a consistent records of patients' conditions and distributed prescription. ",
    examples: [
      {
        title: "Customized Login Page",
        description:
          "I used to rely on bootstrap libraries for styling. Upon completion of this project, I try to style the web application with my own styles.",
        image: require("../assets/img/projects/freemedcure/login_page.png"),
      },
      {
        title: "Add Patient",
        description: "I designed a form for doctors to input patient's data.",
        image: require("../assets/img/projects/freemedcure/patient_add.png"),
      },
      {
        title: "List Patient",
        description:
          "Doctor can operate on patients, like viewing profile or adding a new case. Patients, which are generated by dummy data in this example, are shown in a table with pagination.",
        image: require("../assets/img/projects/freemedcure/patient_list.png"),
      },
      {
        title: "Adding Record / Follow Up",
        description:
          "Doctor add data on this page. As requested by my friend, there is a column on the left which shows the past record for reference.",
        image: require("../assets/img/projects/freemedcure/record_followup.png"),
      },
    ],
  };

  componentDidMount() {
    window.scrollTo(0, 0);
  }

  render() {
    const { title, subtitle } = this.data;
    return (
      <>
        <CurvedHeader title={title} subtitle={subtitle} />
        <div id="freemedcure-wrapper">
          <div className="container" id="implmentation">
            <div className="row align-items-center">
              <div className="col">
                <h3>Implementation</h3>
                <p className="mt-3">
                  This application is developed with Laravel, which is an open
                  source framework for PHP. I stored the data with MySQL
                  database and I manage it through phpMyAdmin. I have used some
                  libraries like bootstrap and jQuery as well.
                </p>
              </div>
            </div>
            <div className="card-deck mt-4 text-center mb-5">
              <div className="card">
                <div className="card-body">
                  <FontAwesomeIcon icon={faLaravel} size="5x" />
                  <h5 className="card-title mt-2">Laravel</h5>
                </div>
              </div>

              <div className="card">
                <div className="card-body">
                  <FontAwesomeIcon icon={faPhp} size="5x" />
                  <h5 className="card-title mt-2">PHP</h5>
                </div>
              </div>

              <div className="card">
                <div className="card-body">
                  <FontAwesomeIcon icon={faBootstrap} size="5x" />
                  <h5 className="card-title mt-2">Bootstrap</h5>
                </div>
              </div>

              <div className="card">
                <div className="card-body">
                  <FontAwesomeIcon icon={faJsSquare} size="5x" />
                  <h5 className="card-title mt-2">jQuery</h5>
                </div>
              </div>

              <div className="card">
                <div className="card-body">
                  <FontAwesomeIcon icon={faDatabase} size="5x" />
                  <h5 className="card-title mt-2">MySQL</h5>
                </div>
              </div>
            </div>
          </div>

          <div id="highlight-section">
            <div className="container">
              <div className="row">
                <div className="col">
                  <h3 className="highlight" className="mt-5">
                    Highlight Features
                  </h3>
                </div>
              </div>
              <p id="description">
                My friend has asked me to build some feature that makes the
                input process faster. I have designed the following features to
                make the system more user-friendly and make the process more
                convenient.
              </p>

              <div className="row my-3 justify-content-center">
                <div className="col-md-6 mb-5 col-12">
                  <h3 id="feature1" className="feature">
                    <span className="yellowTxt">Automatic Increment</span> of
                    Input Rows
                  </h3>
                </div>
                <div className="col-md-6 col-12">
                  <h3 id="feature2" className="feature">
                    <span className="yellowTxt">Auto completion</span> of Text
                    Field
                  </h3>
                </div>
              </div>
            </div>
            <video muted controls loop>
              <source src={this.video} type="video/mp4" />
              Your browser does not support the video tag
            </video>
          </div>

          <div id="gallery-section">
            {this.data.examples.map((item, index) => (
              <div
                className="d-flex flex-column flex-md-row"
                key={`example-${index}`}
              >
                <div
                  className={
                    index % 2 === 0 ? "description" : "description order-md-1"
                  }
                >
                  <h2>{item.title}</h2>
                  <p>{item.description}</p>
                </div>
                <div>
                  <img
                    src={item.image}
                    alt={item.title}
                    className="img-fluid"
                  />
                </div>
              </div>
            ))}
          </div>

          <div id="reflection">
            <div className="container">
              <div className="row">
                <div className="col">
                  <h1>Reflection</h1>
                  <p>
                    First of all, thank you for browsing my web and knowing
                    about me. This project may look easy at your first glaze
                    that it is an online system for inputting data. However,
                    this is quite tricky when I implement it because I have
                    encountered quite a number of problems, from front-end
                    styling to php backend script. I’m so glad that I finally
                    finished a web application that is useful for other people.
                  </p>

                  <p>
                    It is really satisfying to finish this application, but this
                    does not mean it is the end. I will keep improving my
                    programming skills and develope more useful and nice-looking
                    web applications!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* <img
              src={this.backgroundImg.bigCircle}
              className="bigCircle"
              alt="Big Size Circle"
            />
            <img
              src={this.backgroundImg.middleCircle}
              className="middleCircle"
              alt="Middle Size Circle"
            />
            <img
              src={this.backgroundImg.smallCircle}
              className="smallCircle"
              alt="Small Size Circle"
            /> */}
      </>
    );
  }
}

export default FreeMedCure;
